# Form implementation generated from reading ui file 'add_order_window_ui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddOrderWindow(object):
    def setupUi(self, AddOrderWindow):
        AddOrderWindow.setObjectName("AddOrderWindow")
        AddOrderWindow.resize(700, 600)
        AddOrderWindow.setMinimumSize(QtCore.QSize(700, 600))
        AddOrderWindow.setStyleSheet("QWidget{background-color: #FFFFFF;\n"
"font-family: \"Times New Roman\";\n"
"font-size: 13pt;\n"
"color: black}\n"
"QLineEdit{\n"
"border: 1px solid black;\n"
"}\n"
"QPushButton{\n"
"background-color: #00FA9A\n"
"}\n"
"QComboBox{\n"
"border: 1px solid black;\n"
"}\n"
"QDateEdit{\n"
"border: 1px solid black;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(AddOrderWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.go_back_btn = QtWidgets.QPushButton(parent=AddOrderWindow)
        self.go_back_btn.setObjectName("go_back_btn")
        self.verticalLayout_2.addWidget(self.go_back_btn, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.product_cbx_1 = QtWidgets.QComboBox(parent=AddOrderWindow)
        self.product_cbx_1.setObjectName("product_cbx_1")
        self.verticalLayout_2.addWidget(self.product_cbx_1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.product_cbx_2 = QtWidgets.QComboBox(parent=AddOrderWindow)
        self.product_cbx_2.setObjectName("product_cbx_2")
        self.verticalLayout_2.addWidget(self.product_cbx_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.status_cbx = QtWidgets.QComboBox(parent=AddOrderWindow)
        self.status_cbx.setObjectName("status_cbx")
        self.verticalLayout_2.addWidget(self.status_cbx)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.pick_up_point_cbx = QtWidgets.QComboBox(parent=AddOrderWindow)
        self.pick_up_point_cbx.setObjectName("pick_up_point_cbx")
        self.verticalLayout_2.addWidget(self.pick_up_point_cbx)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.label = QtWidgets.QLabel(parent=AddOrderWindow)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.date_order_de = QtWidgets.QDateEdit(parent=AddOrderWindow)
        self.date_order_de.setCalendarPopup(True)
        self.date_order_de.setDate(QtCore.QDate(2026, 4, 9))
        self.date_order_de.setObjectName("date_order_de")
        self.verticalLayout_2.addWidget(self.date_order_de)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.label_2 = QtWidgets.QLabel(parent=AddOrderWindow)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.date_delivery_de = QtWidgets.QDateEdit(parent=AddOrderWindow)
        self.date_delivery_de.setCalendarPopup(True)
        self.date_delivery_de.setDate(QtCore.QDate(2026, 4, 10))
        self.date_delivery_de.setObjectName("date_delivery_de")
        self.verticalLayout_2.addWidget(self.date_delivery_de)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.add_order_btn = QtWidgets.QPushButton(parent=AddOrderWindow)
        self.add_order_btn.setObjectName("add_order_btn")
        self.verticalLayout_2.addWidget(self.add_order_btn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(AddOrderWindow)
        QtCore.QMetaObject.connectSlotsByName(AddOrderWindow)

    def retranslateUi(self, AddOrderWindow):
        _translate = QtCore.QCoreApplication.translate
        AddOrderWindow.setWindowTitle(_translate("AddOrderWindow", "Добавление заказа"))
        self.go_back_btn.setText(_translate("AddOrderWindow", "Назад"))
        self.label.setText(_translate("AddOrderWindow", "Дата заказа"))
        self.label_2.setText(_translate("AddOrderWindow", "Дата доставки"))
        self.add_order_btn.setText(_translate("AddOrderWindow", "Добавить заказ"))
