# Form implementation generated from reading ui file 'add_product_window_ui.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddProductWindow(object):
    def setupUi(self, AddProductWindow):
        AddProductWindow.setObjectName("AddProductWindow")
        AddProductWindow.resize(700, 600)
        AddProductWindow.setMinimumSize(QtCore.QSize(700, 600))
        AddProductWindow.setStyleSheet("QWidget{background-color: #FFFFFF;\n"
"font-family: \"Times New Roman\";\n"
"font-size: 13pt;\n"
"color: black}\n"
"QLineEdit{\n"
"border: 1px solid black;\n"
"}\n"
"QPushButton{\n"
"background-color: #00FA9A\n"
"}\n"
"QComboBox{\n"
"border: 1px solid black;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(AddProductWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.go_back_btn = QtWidgets.QPushButton(parent=AddProductWindow)
        self.go_back_btn.setObjectName("go_back_btn")
        self.verticalLayout_3.addWidget(self.go_back_btn, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.photo_l = QtWidgets.QLabel(parent=AddProductWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.photo_l.sizePolicy().hasHeightForWidth())
        self.photo_l.setSizePolicy(sizePolicy)
        self.photo_l.setMinimumSize(QtCore.QSize(300, 200))
        self.photo_l.setMaximumSize(QtCore.QSize(300, 200))
        self.photo_l.setStyleSheet("border: 1px solid black;")
        self.photo_l.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.photo_l.setObjectName("photo_l")
        self.horizontalLayout.addWidget(self.photo_l)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.type_cbx = QtWidgets.QComboBox(parent=AddProductWindow)
        self.type_cbx.setObjectName("type_cbx")
        self.verticalLayout_2.addWidget(self.type_cbx)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.category_cbx = QtWidgets.QComboBox(parent=AddProductWindow)
        self.category_cbx.setObjectName("category_cbx")
        self.verticalLayout_2.addWidget(self.category_cbx)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.description_le = QtWidgets.QLineEdit(parent=AddProductWindow)
        self.description_le.setObjectName("description_le")
        self.verticalLayout_2.addWidget(self.description_le)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.producer_cbx = QtWidgets.QComboBox(parent=AddProductWindow)
        self.producer_cbx.setObjectName("producer_cbx")
        self.verticalLayout_2.addWidget(self.producer_cbx)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.supplier_cbx = QtWidgets.QComboBox(parent=AddProductWindow)
        self.supplier_cbx.setObjectName("supplier_cbx")
        self.verticalLayout_2.addWidget(self.supplier_cbx)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.price_le = QtWidgets.QLineEdit(parent=AddProductWindow)
        self.price_le.setObjectName("price_le")
        self.verticalLayout_2.addWidget(self.price_le)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.unit_measure_le = QtWidgets.QLineEdit(parent=AddProductWindow)
        self.unit_measure_le.setObjectName("unit_measure_le")
        self.verticalLayout_2.addWidget(self.unit_measure_le)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.amount_le = QtWidgets.QLineEdit(parent=AddProductWindow)
        self.amount_le.setObjectName("amount_le")
        self.verticalLayout_2.addWidget(self.amount_le)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.discount_le = QtWidgets.QLineEdit(parent=AddProductWindow)
        self.discount_le.setObjectName("discount_le")
        self.verticalLayout_2.addWidget(self.discount_le)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.add_product_btn = QtWidgets.QPushButton(parent=AddProductWindow)
        self.add_product_btn.setObjectName("add_product_btn")
        self.verticalLayout_2.addWidget(self.add_product_btn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem10)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(AddProductWindow)
        QtCore.QMetaObject.connectSlotsByName(AddProductWindow)

    def retranslateUi(self, AddProductWindow):
        _translate = QtCore.QCoreApplication.translate
        AddProductWindow.setWindowTitle(_translate("AddProductWindow", "Добавление товара"))
        self.go_back_btn.setText(_translate("AddProductWindow", "Назад"))
        self.photo_l.setText(_translate("AddProductWindow", "Загрузить фото..."))
        self.description_le.setPlaceholderText(_translate("AddProductWindow", "Описание"))
        self.price_le.setPlaceholderText(_translate("AddProductWindow", "Цена"))
        self.unit_measure_le.setPlaceholderText(_translate("AddProductWindow", "Единица измерения"))
        self.amount_le.setPlaceholderText(_translate("AddProductWindow", "Количество на складе"))
        self.discount_le.setPlaceholderText(_translate("AddProductWindow", "Действующая скидка"))
        self.add_product_btn.setText(_translate("AddProductWindow", "Добавить товар"))
