# Form implementation generated from reading ui file 'auth_window_ui.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AuthorizationWindow(object):
    def setupUi(self, AuthorizationWindow):
        AuthorizationWindow.setObjectName("AuthorizationWindow")
        AuthorizationWindow.resize(450, 350)
        AuthorizationWindow.setMinimumSize(QtCore.QSize(450, 350))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        AuthorizationWindow.setFont(font)
        AuthorizationWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        AuthorizationWindow.setWindowIcon(icon)
        AuthorizationWindow.setAutoFillBackground(False)
        AuthorizationWindow.setStyleSheet("QWidget{background-color: #FFFFFF;\n"
"font-family: \"Times New Roman\";\n"
"font-size: 13pt;\n"
"color: black}\n"
"QLineEdit{\n"
"border: 1px solid black;\n"
"}\n"
"QPushButton{\n"
"background-color: #00FA9A\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(AuthorizationWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_le = QtWidgets.QLineEdit(parent=AuthorizationWindow)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.login_le.setFont(font)
        self.login_le.setStyleSheet("")
        self.login_le.setObjectName("login_le")
        self.verticalLayout.addWidget(self.login_le)
        self.password_le = QtWidgets.QLineEdit(parent=AuthorizationWindow)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.password_le.setFont(font)
        self.password_le.setStyleSheet("\n"
"")
        self.password_le.setObjectName("password_le")
        self.verticalLayout.addWidget(self.password_le)
        self.auth_btn = QtWidgets.QPushButton(parent=AuthorizationWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.auth_btn.sizePolicy().hasHeightForWidth())
        self.auth_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.auth_btn.setFont(font)
        self.auth_btn.setStyleSheet("")
        self.auth_btn.setObjectName("auth_btn")
        self.verticalLayout.addWidget(self.auth_btn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.guest_btn = QtWidgets.QPushButton(parent=AuthorizationWindow)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.guest_btn.setFont(font)
        self.guest_btn.setStyleSheet("")
        self.guest_btn.setObjectName("guest_btn")
        self.verticalLayout.addWidget(self.guest_btn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.retranslateUi(AuthorizationWindow)
        QtCore.QMetaObject.connectSlotsByName(AuthorizationWindow)

    def retranslateUi(self, AuthorizationWindow):
        _translate = QtCore.QCoreApplication.translate
        AuthorizationWindow.setWindowTitle(_translate("AuthorizationWindow", "Авторизация"))
        self.login_le.setPlaceholderText(_translate("AuthorizationWindow", "Введите логин"))
        self.password_le.setPlaceholderText(_translate("AuthorizationWindow", "Введите пароль"))
        self.auth_btn.setText(_translate("AuthorizationWindow", "Войти"))
        self.guest_btn.setText(_translate("AuthorizationWindow", "Войти как гость"))
