# Form implementation generated from reading ui file 'view/edit_order_window_ui.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditOrderWindow(object):
    def setupUi(self, EditOrderWindow):
        EditOrderWindow.setObjectName("EditOrderWindow")
        EditOrderWindow.resize(600, 500)
        EditOrderWindow.setMinimumSize(QtCore.QSize(600, 500))
        EditOrderWindow.setStyleSheet("QWidget{background-color: #FFFFFF;\n"
"font-family: \"Times New Roman\";\n"
"font-size: 13pt;\n"
"color: black}\n"
"QLineEdit{\n"
"border: 1px solid black;\n"
"}\n"
"QPushButton{\n"
"background-color: #00FA9A\n"
"}\n"
"QComboBox{\n"
"border: 1px solid black;\n"
"}\n"
"QDateEdit{\n"
"border: 1px solid black;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(EditOrderWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.go_back_btn = QtWidgets.QPushButton(parent=EditOrderWindow)
        self.go_back_btn.setObjectName("go_back_btn")
        self.verticalLayout_2.addWidget(self.go_back_btn, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.id_le = QtWidgets.QLineEdit(parent=EditOrderWindow)
        self.id_le.setEnabled(False)
        self.id_le.setText("")
        self.id_le.setPlaceholderText("")
        self.id_le.setObjectName("id_le")
        self.verticalLayout_2.addWidget(self.id_le)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.status_cbx = QtWidgets.QComboBox(parent=EditOrderWindow)
        self.status_cbx.setObjectName("status_cbx")
        self.verticalLayout_2.addWidget(self.status_cbx)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.pick_up_point_cbx = QtWidgets.QComboBox(parent=EditOrderWindow)
        self.pick_up_point_cbx.setObjectName("pick_up_point_cbx")
        self.verticalLayout_2.addWidget(self.pick_up_point_cbx)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.label = QtWidgets.QLabel(parent=EditOrderWindow)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.date_order_de = QtWidgets.QDateEdit(parent=EditOrderWindow)
        self.date_order_de.setCalendarPopup(True)
        self.date_order_de.setObjectName("date_order_de")
        self.verticalLayout_2.addWidget(self.date_order_de)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.label_2 = QtWidgets.QLabel(parent=EditOrderWindow)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.date_delivery_de = QtWidgets.QDateEdit(parent=EditOrderWindow)
        self.date_delivery_de.setCalendarPopup(True)
        self.date_delivery_de.setObjectName("date_delivery_de")
        self.verticalLayout_2.addWidget(self.date_delivery_de)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.products_in_order_l = QtWidgets.QLabel(parent=EditOrderWindow)
        self.products_in_order_l.setText("")
        self.products_in_order_l.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.products_in_order_l.setObjectName("products_in_order_l")
        self.verticalLayout_2.addWidget(self.products_in_order_l)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.save_order_btn = QtWidgets.QPushButton(parent=EditOrderWindow)
        self.save_order_btn.setObjectName("save_order_btn")
        self.verticalLayout_2.addWidget(self.save_order_btn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.delete_order_btn = QtWidgets.QPushButton(parent=EditOrderWindow)
        self.delete_order_btn.setObjectName("delete_order_btn")
        self.verticalLayout_2.addWidget(self.delete_order_btn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(EditOrderWindow)
        QtCore.QMetaObject.connectSlotsByName(EditOrderWindow)

    def retranslateUi(self, EditOrderWindow):
        _translate = QtCore.QCoreApplication.translate
        EditOrderWindow.setWindowTitle(_translate("EditOrderWindow", "Редактирование заказа"))
        self.go_back_btn.setText(_translate("EditOrderWindow", "Назад"))
        self.label.setText(_translate("EditOrderWindow", "Дата заказа"))
        self.label_2.setText(_translate("EditOrderWindow", "Дата доставки"))
        self.save_order_btn.setText(_translate("EditOrderWindow", "Сохранить заказ"))
        self.delete_order_btn.setText(_translate("EditOrderWindow", "Удалить заказ"))
