# Form implementation generated from reading ui file 'orders_window_ui.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OrdersWindow(object):
    def setupUi(self, OrdersWindow):
        OrdersWindow.setObjectName("OrdersWindow")
        OrdersWindow.resize(700, 600)
        OrdersWindow.setMinimumSize(QtCore.QSize(700, 600))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        OrdersWindow.setFont(font)
        OrdersWindow.setStyleSheet("QWidget{background-color: #FFFFFF;\n"
"font-family: \"Times New Roman\";\n"
"font-size: 13pt;\n"
"color: black}\n"
"QLineEdit{\n"
"border: 1px solid black;\n"
"}\n"
"QPushButton{\n"
"background-color: #00FA9A\n"
"}\n"
"QComboBox{\n"
"border: 1px solid black;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(OrdersWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.go_back_btn = QtWidgets.QPushButton(parent=OrdersWindow)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.go_back_btn.setFont(font)
        self.go_back_btn.setStyleSheet("background-color: rgb(0, 250, 154)")
        self.go_back_btn.setObjectName("go_back_btn")
        self.gridLayout.addWidget(self.go_back_btn, 2, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.open_add_order_window_btn = QtWidgets.QPushButton(parent=OrdersWindow)
        self.open_add_order_window_btn.setObjectName("open_add_order_window_btn")
        self.gridLayout.addWidget(self.open_add_order_window_btn, 2, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout.addLayout(self.gridLayout)
        self.scrollArea = QtWidgets.QScrollArea(parent=OrdersWindow)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollWidget = QtWidgets.QWidget()
        self.scrollWidget.setGeometry(QtCore.QRect(0, 0, 674, 541))
        self.scrollWidget.setObjectName("scrollWidget")
        self.scrollArea.setWidget(self.scrollWidget)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(OrdersWindow)
        QtCore.QMetaObject.connectSlotsByName(OrdersWindow)

    def retranslateUi(self, OrdersWindow):
        _translate = QtCore.QCoreApplication.translate
        OrdersWindow.setWindowTitle(_translate("OrdersWindow", "Список заказов"))
        self.go_back_btn.setText(_translate("OrdersWindow", "Назад"))
        self.open_add_order_window_btn.setText(_translate("OrdersWindow", "Добавить заказ"))
