# Form implementation generated from reading ui file 'products_window_ui.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProductsWindow(object):
    def setupUi(self, ProductsWindow):
        ProductsWindow.setObjectName("ProductsWindow")
        ProductsWindow.resize(700, 600)
        ProductsWindow.setMinimumSize(QtCore.QSize(700, 600))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        ProductsWindow.setFont(font)
        ProductsWindow.setStyleSheet("QWidget{background-color: #FFFFFF;\n"
"font-family: \"Times New Roman\";\n"
"font-size: 13pt;\n"
"color: black}\n"
"QLineEdit{\n"
"border: 1px solid black;\n"
"}\n"
"QPushButton{\n"
"background-color: #00FA9A\n"
"}\n"
"QComboBox{\n"
"border: 1px solid black;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(ProductsWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo_l = QtWidgets.QLabel(parent=ProductsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_l.sizePolicy().hasHeightForWidth())
        self.logo_l.setSizePolicy(sizePolicy)
        self.logo_l.setMaximumSize(QtCore.QSize(30, 30))
        self.logo_l.setText("")
        self.logo_l.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.logo_l.setScaledContents(True)
        self.logo_l.setObjectName("logo_l")
        self.verticalLayout.addWidget(self.logo_l, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.go_back_btn = QtWidgets.QPushButton(parent=ProductsWindow)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.go_back_btn.setFont(font)
        self.go_back_btn.setStyleSheet("background-color: rgb(0, 250, 154)")
        self.go_back_btn.setObjectName("go_back_btn")
        self.gridLayout.addWidget(self.go_back_btn, 2, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.sort_cbx = QtWidgets.QComboBox(parent=ProductsWindow)
        self.sort_cbx.setObjectName("sort_cbx")
        self.gridLayout.addWidget(self.sort_cbx, 3, 0, 1, 1)
        self.user_name_l = QtWidgets.QLabel(parent=ProductsWindow)
        self.user_name_l.setText("")
        self.user_name_l.setObjectName("user_name_l")
        self.gridLayout.addWidget(self.user_name_l, 2, 3, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight)
        self.search_le = QtWidgets.QLineEdit(parent=ProductsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_le.sizePolicy().hasHeightForWidth())
        self.search_le.setSizePolicy(sizePolicy)
        self.search_le.setObjectName("search_le")
        self.gridLayout.addWidget(self.search_le, 3, 3, 1, 1)
        self.filter_cbx = QtWidgets.QComboBox(parent=ProductsWindow)
        self.filter_cbx.setObjectName("filter_cbx")
        self.gridLayout.addWidget(self.filter_cbx, 3, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.open_add_product_window_btn = QtWidgets.QPushButton(parent=ProductsWindow)
        self.open_add_product_window_btn.setObjectName("open_add_product_window_btn")
        self.horizontalLayout.addWidget(self.open_add_product_window_btn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.open_orders_window_btn = QtWidgets.QPushButton(parent=ProductsWindow)
        self.open_orders_window_btn.setObjectName("open_orders_window_btn")
        self.horizontalLayout.addWidget(self.open_orders_window_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.scrollArea = QtWidgets.QScrollArea(parent=ProductsWindow)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollWidget = QtWidgets.QWidget()
        self.scrollWidget.setGeometry(QtCore.QRect(0, 0, 674, 477))
        self.scrollWidget.setObjectName("scrollWidget")
        self.scrollArea.setWidget(self.scrollWidget)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(ProductsWindow)
        QtCore.QMetaObject.connectSlotsByName(ProductsWindow)

    def retranslateUi(self, ProductsWindow):
        _translate = QtCore.QCoreApplication.translate
        ProductsWindow.setWindowTitle(_translate("ProductsWindow", "Список товаров"))
        self.go_back_btn.setText(_translate("ProductsWindow", "Выйти"))
        self.search_le.setPlaceholderText(_translate("ProductsWindow", "Поиск"))
        self.open_add_product_window_btn.setText(_translate("ProductsWindow", "Добавить товар"))
        self.open_orders_window_btn.setText(_translate("ProductsWindow", "Заказы"))
